import "./globals.css";
import ThemeProvide from "../components/component/Header/ThemeProvide";
import ThemeSwitcher from "@/components/component/Header/ThemeSwitcher";
import Header from "@/components/component/Header/Header";
import { Montserrat } from "next/font/google";
import { BootomFooter } from "@/components/component/Footer/Footer";

export const metadata = {
  title: "MakeMyTrip App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body>
        <ThemeProvide>
          <Header />
          <ThemeSwitcher />
          {children}
          <BootomFooter />
        </ThemeProvide>
      </body>
    </html>
  );
}
