import "./globals.css";
import ThemeProvide from "../components/component/Header/ThemeProvide";
import ThemeSwitcher from "@/components/component/Header/ThemeSwitcher";
import Header from "@/components/component/Header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvide>
          <Header />
          <ThemeSwitcher />
          {children}
        </ThemeProvide>
      </body>
    </html>
  );
}
